import type { ThemeConfig } from 'antd';

export const appThemeTokens = {
  bgPage: '#0b090f',
  bgPageDeep: '#0c0a0f',
  bgSurface: '#16131c',
  bgSurfaceSoft: '#1c1824',
  bgSurfaceRaised: '#181421',
  bgControl: '#141218',
  bgControlDeep: '#110e16',
  bgControlHover: '#211f24',
  bgControlMuted: '#36343a',
  borderFaint: 'rgba(255, 255, 255, 0.05)',
  borderSoft: 'rgba(255, 255, 255, 0.08)',
  borderControl: 'rgba(255, 255, 255, 0.1)',
  borderControlHover: 'rgba(255, 255, 255, 0.14)',
  borderActive: 'rgba(207, 188, 255, 0.45)',
  primary: '#6750a4',
  primaryLight: '#cfbcff',
  primaryContrast: '#381e72',
  textPrimary: '#ffffff',
  textBody: '#e6e0e9',
  textSecondary: '#cbc4d2',
  textMuted: 'rgba(203, 196, 210, 0.55)',
  textDescription: 'rgba(203, 196, 210, 0.65)',
  textFaint: 'rgba(203, 196, 210, 0.35)',
  textPlaceholder: 'rgba(203, 196, 210, 0.32)',
  success: '#34d399',
  successStrong: '#00e676',
  warning: '#e7c365',
  warningStrong: '#f59e0b',
  danger: '#f87171',
  dangerStrong: '#ff6b8a',
  risk: '#fb7185',
  info: '#58c7ff',
  radiusSm: 8,
  radiusMd: 12,
  radiusLg: 16,
  shadowCard: '0 18px 60px rgba(0, 0, 0, 0.22)',
  shadowModal: '0 25px 50px -12px rgba(0, 0, 0, 0.75)',
  fontFamily: '"Inter", ui-sans-serif, system-ui, sans-serif',
  fontSizeBody: 13,
  fontSizeTableHeader: 12,
  fontSizeCaption: 12,
  fontSizeMin: 11,
};

export const globalTokens: ThemeConfig['token'] = {
  colorBgBase: appThemeTokens.bgPageDeep,
  colorBgContainer: appThemeTokens.bgSurfaceRaised,
  colorBgElevated: appThemeTokens.bgSurfaceRaised,
  colorBorder: appThemeTokens.borderControl,
  colorBorderSecondary: appThemeTokens.borderFaint,
  colorError: appThemeTokens.danger,
  colorInfo: appThemeTokens.info,
  colorPrimary: appThemeTokens.primary,
  colorPrimaryActive: appThemeTokens.primary,
  colorPrimaryHover: appThemeTokens.primaryLight,
  colorSuccess: appThemeTokens.success,
  colorText: appThemeTokens.textBody,
  colorTextBase: appThemeTokens.textBody,
  colorTextDescription: appThemeTokens.textDescription,
  colorTextDisabled: appThemeTokens.textFaint,
  colorTextPlaceholder: appThemeTokens.textPlaceholder,
  colorWarning: appThemeTokens.warningStrong,
  borderRadius: appThemeTokens.radiusMd,
  borderRadiusLG: appThemeTokens.radiusLg,
  borderRadiusSM: appThemeTokens.radiusSm,
  fontFamily: appThemeTokens.fontFamily,
  fontSize: appThemeTokens.fontSizeBody,
  fontSizeSM: appThemeTokens.fontSizeCaption,
};
